package Client;

public enum MessageType {
	AUTHENTICATION_TOKEN,
    PROTOCOL_VERSION,
    GRAPHIC_DATA,
    RESOURCE_DATA,
    LOGIN_REQUEST,
    CHARACTER_DATA,
    CHARACTER_MOVE,
    TERRAIN_REQUEST,
    DATA_UPDATE,
	CHAR_UPDATE,
	CHAR_GRPAHICS
}
